### ISSUE TITLE
Failed to build on Mac OS 10.11.5

### ISSUE THREAD

**Issue by ferhtgoldaraz** [yyuu/pyenv#640]
I'm unable to build on Mac OS 10.11.5

This is the last part of the build log:

```bash
clang -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/Fer/.pyenv/versions/2.7.11/lib  -u _PyMac_Error -o python.exe \
                        Modules/python.o \
                        libpython2.7.a -ldl  -framework CoreFoundation
ld: warning: ignoring file libpython2.7.a, file was built for archive which is not the architecture being linked (x86_64): libpython2.7.a
Undefined symbols for architecture x86_64:
  "_PyMac_Error", referenced from:
     -u command line option
  "_Py_Main", referenced from:
      _main in python.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
````

Things Ive tried:

`brew link --force readline` and `brew link --force openssl` didn't work.

About `_PyMac_Error` and from info [here](https://bugs.python.org/issue3588), I tried

```python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("LINKFORSHARED")
>>> '-u _PyMac_Error /System/Library/Frameworks/Python.framework/Versions/2.7/Python'
```

So that seems to be fine, to confirm:

```bash
$ ls -lah "/System/Library/Frameworks/Python.framework/Versions/2.7/Python"
-rwxr-xr-x 1 root wheel 2.6M mar 12 09:09 /System/Library/Frameworks/Python.framework/Versions/2.7/Python
```

Lastly, I'm no compiling expert, in fact I avoid it, but I believe the -L flag, which I can't find in the clang man page but I assume to mean what means in gcc for maybe compatibility reasons, includes libraries for linking, or directories, or something related to this...

Is that right?

The line in the log that says `-L/Users/Fer/.pyenv/versions/2.7.11/lib` wouldn't make sense to me then, since that folder doesn't exist yet, as I have not been able to install any pyenv managed python yet.

This is what I find right now to be most interesing:

```bash
$ ls /Users/Fer/.pyenv/versions/2.7.11/lib
ls: cannot access '/Users/Fer/.pyenv/versions/2.7.11/lib': No such file or directory
```

Some more info:

```bash
$ command -v pyenv
pyenv
$ echo $PATH | tr ':' '\n'
/Users/Fer/.pyenv/shims
/Users/Fer/.pyenv/bin
/Users/Fer/.nvm/versions/node/v6.2.1/bin
/usr/local/bin
/Users/Fer/bin
/usr/local/opt/coreutils/libexec/gnubin
/usr/local/opt/gnu-sed/libexec/gnubin
/usr/local/opt/gnu-tar/libexec/gnubin
/usr/bin
/bin
/usr/sbin
/sbin
$ uname -a
Darwin fer-work-mac 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin
```

If anyone wants more info I'll do my best to provide it.

**Comment by yyuu** [comment]
`-L` is an linker option and you'd need to look for ld(1) instead of clang(1). Anyway I guess something is wrong on your environment or build options. The output of the following might help further debugging. Anyway this must not be a kind of pyenv's issue.

* `env` (remove credentials before pasting!)
* `sw_ver`
* `clang --version`
* `pyenv install -v 2.7.11`

**Comment by jenhsun** [comment]
Here is my way to install pyenv
`env PYTHON_CONFIGURE_OPTS="--enable-framework=$(pyenv root)/versions/3.5.2 --enable-toolbox-glue --enable-big-digits --enable-unicode --with-threads" pyenv install 3.5.2
`

**Comment by DuncanHills** [comment]
For anyone else that runs into this problem, I had to `brew reinstall binutils` because the old version had created symlinks to the homebrew `ar`, `ranlib`, etc, in the homebrew bin directory, whereas new versions are cask only. The homebrew versions created archive files during the python build that caused problems.

**Comment by ubergesundheit** [comment]
I had this issue as well. A comment from https://github.com/pyenv/pyenv/issues/1236 solved my problem on macos 10.14.2

    brew uninstall binutils

**Comment by kost** [comment]
You don't have to uninstall, unlink is enough:

```
brew unlink binutils
Unlinking /usr/local/Cellar/binutils/2.33.1... 121 symlinks removed
```
